version: "3.9"
services:
  meglioquestio_backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true
    command: "php artisan serve --host=0.0.0.0"
    depends_on:
      - meglioquestio_db
    networks:
      - meglioquestio

  meglioquestio_db:
    image: mysql:8
    restart: always
    container_name: meglioquestio_db
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_DATABASE: meglioquestio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    networks:
      - meglioquestio

networks:
  meglioquestio:
